// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChaptersController from "./chapters_controller"
application.register("chapters", ChaptersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ResultscrollController from "./resultscroll_controller"
application.register("resultscroll", ResultscrollController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)
