{
  "executionTime": 0,
  "id": "KALICONT000005635613",
  "titre": "Convention collective nationale des industries chimiques et connexes du 30 décembre 1952. Étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
  "numeroTexte": "IDCC 44",
  "num": "44",
  "nature": "IDCC",
  "categorisation": [
    "Industries chimiques et connexes"
  ],
  "activitePro": [
    "Industries chimiques et connexes"
  ],
  "sections": [
    {
      "executionTime": 0,
      "dereferenced": false,
      "id": "KALITEXT000005677744",
      "cid": "KALITEXT000005677744",
      "intOrdre": 0,
      "etat": "VIGUEUR_ETEN",
      "title": "Texte de base : Convention collective nationale des industries chimiques et connexes du 30 décembre 1952. Étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
      "dateModif": null,
      "dateDebut": null,
      "dateFin": null,
      "sectionConsultee": false,
      "sections": [
        {
          "executionTime": 0,
          "dereferenced": false,
          "id": "KALISCTA000005722130",
          "cid": "KALISCTA000005722130",
          "intOrdre": 42949,
          "etat": "VIGUEUR_ETEN",
          "title": "Clauses générales",
          "dateModif": null,
          "dateDebut": null,
          "dateFin": null,
          "sectionConsultee": false,
          "sections": [
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751407",
              "cid": "KALISCTA000005751407",
              "intOrdre": 42949,
              "etat": "VIGUEUR_NON_ETEN",
              "title": "Objet de la convention - Champ d'application",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846007",
                  "cid": "KALIARTI000005846007",
                  "intOrdre": 42949,
                  "etat": "REMPLACE",
                  "num": "1",
                  "path": "/KALISCTA000005722130/KALISCTA000005751407/KALIARTI000005846007",
                  "pathTitle": [
                    "Clauses générales",
                    "Objet de la convention - Champ d'application"
                  ],
                  "content": "<p></p>   1. La présente convention collective nationale des industries chimiques conclue en application de la loi du 11 février 1950 règle sur le territoire métropolitain les rapports de travail entre les employeurs et le personnel au sein des établissements dont l'activité principale relève des industries et commerces chimiques figurant à l'annexe I.<p></p><p></p>   2. Des avenants à la présente convention fixent les conditions particulières de travail des différentes catégories de personnel.<p></p><font color='808080'><em>   NOTA. L'avenant du 23 octobre 1991 en annexe annule le présent champ d'application.<p></p></em></font>",
                  "nota": "   NOTA. L'avenant du 23 octobre 1991 en annexe annule le présent champ d'application.<p></p>",
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": null,
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                },
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846008",
                  "cid": "KALIARTI000005846007",
                  "intOrdre": 85898,
                  "etat": "VIGUEUR_ETEN",
                  "num": "1er",
                  "path": "/KALISCTA000005722130/KALISCTA000005751407/KALIARTI000005846008",
                  "pathTitle": [
                    "Clauses générales",
                    "Objet de la convention - Champ d'application"
                  ],
                  "content": "<p>1. La présente convention collective nationale des industries chimiques conclue en application de la loi du 11 février 1950 règle sur le territoire métropolitain les rapports de travail entre les employeurs et le personnel au sein des établissements adhérents aux organisations patronales signataires dont l'activité principale relève des industries et commerces chimiques figurant à l'annexe I.</p><p>2. Des avenants à la présente convention fixent les conditions particulières de travail des différentes catégories de personnel.</p>",
                  "nota": "   NOTA : (1) Termes exclus de l'extension par arrêté du 13 novembre 1956.<p></p>",
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "2.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 *étendue avec exclusions par arrêté du 13 novembre 1956 JONC 12 décembre 1956*",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": null,
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                },
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846009",
                  "cid": "KALIARTI000005846007",
                  "intOrdre": 128847,
                  "etat": "MODIFIE",
                  "num": "1",
                  "path": "/KALISCTA000005722130/KALISCTA000005751407/KALIARTI000005846009",
                  "pathTitle": [
                    "Clauses générales",
                    "Objet de la convention - Champ d'application"
                  ],
                  "content": "Article 1er<p></p><p></p>   Le champ d'application professionnel de la convention collective nationale et des accords collectifs des industries chimiques est modifié comme suit :<p></p><p></p>   Le champ d'application de la convention collective nationale et des accords collectifs des industries chimiques est défini par référence à la nomenclature d'activités française instituée par le décret n° 92-1129 du 2 octobre 1992 et entrée en vigueur le 1er janvier 1993.<p></p><p></p>   Entrent dans le présent champ d'application :<p></p><p></p>   1. Les établissements et leurs annexes dont l'activité principale relève des classes énumérées ci-dessous ainsi que les holdings et sièges sociaux dont ils dépendent, sous réserve de dispositions particulières prévues dans certaines classes, notamment celles figurant au paragraphe III.<p></p><p></p>   2. Les établissements de commerce de gros dont l'activité principale porte sur la manipulation et la vente de produits dont la fabrication est visée par la nomenclature ci-dessous - notamment ceux qui relèvent de la classe 51.5 L - sous réserve des précisions apportées pour la classe 51.4 L et à l'exclusion des grossistes des corps gras.<p></p><p></p>I. - ACTIVITES COUVERTES PAR L'U.I.C.<p></p><p></p><p></p>   FABRICATION DE PRODUITS AMYLACES<p></p><p></p>   CODE N.A.F 15.6 D<p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion des amidonneries de blé et de riz.<p></p><p></p><p></p>   INDUSTRIES ALIMENTAIRES N.C.A<p></p><p></p>   CODE N.A.F. 15.8 V <p></p><p></p>   Est visée dans cette classe l'activité de fabrication d'additifs et épaississants alimentaires. <p></p><p></p><p></p>   PRODUCTION D'ALCOOL ETHYLIQUE DE FERMENTATION ;<p></p><p></p>   CODE N.A.F 15.9 D <p></p><p></p>   Est visée dans cette classe l'activité de dénaturation d'alcool éthylique. <p></p><p></p><p></p>   COKEFACTION ;<p></p><p></p>   CODE N.A.F 23.1 Z <p></p><p></p>   Est visée dans cette classe l'activité de production de goudrons. <p></p><p></p>   ELABORATION ET TRANSFORMATION DE MATIERES NUCLEAIRES<p></p><p></p>   CODE N.A.F 23.3 Z <p></p><p></p>   Est visée dans cette classe l'activité de conversion du minerai d'uranium en hexafluorure.<p></p><p></p><p></p>   FABRICATION DE GAZ INDUSTRIELS.<p></p><p></p>   CODE N.A.F 24.1 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE COLORANTS ET DE PIGMENTS.<p></p><p></p>   CODE N.A.F 24.1 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION D'AUTRES PRODUITS CHIMIQUES INORGANIQUES DE BASE.<p></p><p></p>   Sont visées toutes les activités comprises dans cette classe.    CODE N.A.F 24.1 E <p></p><p></p>    FABRICATION D'AUTRES PRODUITS CHIMIQUES ORGANIQUES DE BASE.<p></p><p></p>   CODE N.A.F 24.1 G <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la production de charbon de bois à usage domestique non liée à la valorisation des jus pyroligneux.<p></p><p></p><p></p>   FABRICATION DE PRODUITS AZOTES ET D'ENGRAIS.<p></p><p></p>   CODE N.A.F 24.1 J <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE MATIERES PLASTIQUES DE BASE.<p></p><p></p>   CODE N.A.F 24.1 L <p></p><p></p>   En l'absence d'accord entre les parties signataires sur la \" préparation des mélanges de matières plastiques de base, colorées ou non \" il a été convenu de différer la rédaction définitive de cette classe. Toutefois, il a été convenu que toutes les autres activités de cette classe sont incluses dans le champ d'application.<p></p><p></p><p></p>   FABRICATION DE CAOUTCHOUC SYNTHETIQUE.<p></p><p></p>   CODE N.A.F 24.1 N <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE PRODUITS AGROCHIMIQUES.<p></p><p></p>   CODE N.A.F 24.2 Z <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE PRODUITS PHARMACEUTIQUES DE BASE.<p></p><p></p>   CODE N.A.F 24.4 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la transformation du sang humain et de la fabrication de ses dérivés.<p></p><p></p><p></p>   FABRICATION DE SAVONS, DETERGENTS ET PRODUITS D'ENTRETIEN.<p></p><p></p>   CODE N.A.F 24.5 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la fabrication de savons et de la fabrication de préparations détergentes ou adoucissantes pour la lessive, la vaisselle, etc. qui sont visées dans le paragraphe II du présent champ d'application.<p></p><p></p><p></p>   FABRICATION DE PRODUITS EXPLOSIFS.<p></p><p></p>   CODE N.A.F 24.6 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION D'HUILES ESSENTIELLES.<p></p><p></p>   CODE N.A.F 24.6 E <p></p> Sont visées toutes les activités comprises dans cette classe.<p></p><p></p>    FABRICATION DE PRODUITS CHIMIQUES POUR LA PHOTOGRAPHIE.<p></p><p></p>   CODE N.A.F 24.6 G <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE SUPPORTS DE DONNEES.<p></p><p></p>   CODE N.A.F 24.6 J <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. Toutefois, les établissements concernés qui, à la date d'entrée en vigueur du présent accord, appliquaient le dispositif conventionnel de la métallurgie, pourront continuer à l'appliquer.<p></p><p></p><p></p>   FABRICATION DE PRODUITS CHIMIQUES à USAGE INDUSTRIEL.<p></p><p></p>   CODE N.A.F 24.6 L <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, y compris :<p></p><p></p>   - la fabrication de carburants et de lubrifiants de synthèse ;<p></p><p></p>   - le traitement des schistes bitumineux.<p></p><p></p><p></p>   FABRICATION DE PRODUITS ABRASIFS.<p></p><p></p>   CODE N.A.F 26.8 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe.<p></p><p></p><p></p>   FABRICATION DE PRODUITS MINERAUX NON METALLIQUES N.C.A.<p></p><p></p>   CODE N.A.F 26.8 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exception d'une part de la fabrication de garnitures de friction et de pièces pour ces garnitures, d'autre part de la fabrication d'argile expansée.<p></p><p></p><p></p>   AUTRES ACTIVITES MANUFACTURIERES N.C.A.<p></p><p></p>   CODE N.A.F 36.6 E <p></p><p></p>   Sont visées dans cette classe, d'une part, les activités de fabrication d'allumettes, d'autre part, les activités de fabrication d'articles pour écrire, de rubans pour machine à écrire, de tampons encreurs, dateurs et articles similaires.<p></p><p></p><p></p>   RECUPERATION DE MATIERES NON METALLIQUES RECYCLABLES.<p></p><p></p>   CODE N.A.F 37.2 Z <p></p><p></p>   Est visée dans cette classe l'activité de récupération à partir de déchets contenant des produits chimiques.<p></p><p></p><p></p>   COMMERCE DE GROS COMBUSTIBLES.<p></p><p></p>   CODE N.A.F 51.5 A <p></p><p></p>   Sont visées dans ce groupe les entreprises de commerce de gros de produits pétroliers qui, avant le 8 août 1990, appliquaient la convention collective nationale des industries chimiques.<p></p><p></p>    ELIMINATION ET TRAITEMENT DES AUTRES DECHETS.<p></p><p></p>   CODE N.A.F 90.0 C <p></p><p></p>   Sont visées dans cette classe les activités ayant trait :<p></p><p></p>   - au traitement et à l'élimination des déchets industriels, solides ou liquides,  nécessitant un traitement spécifique ;<p></p><p></p>   - au traitement de déchets toxiques et/ou de sols pollués ;<p></p><p></p>   - à la gestion des centres techniques d'enfouissement de déchets ;<p></p> - au stockage souterrain de déchets.<p></p><p></p>II. - ACTIVITES COUVERTES PAR UN SYNDICAT PATRONAL ASSOCIE<p></p><p></p>   a) Electrométallurgiques, électrochimiques et connexes (Fédération nationale des industries).<p></p><p></p><p></p>   FABRICATION DE PRODUITS MINERAUX NON METALLIQUES N.C.A.<p></p><p></p>   CODE N.A.F 26.8 C <p></p><p></p>   Sont visées dans cette classe les activités de :<p></p><p></p>   - fabrication de corindon ;<p></p><p></p>   - fabrication d'articles en graphite et carbone.<p></p><p></p><p></p>   PRODUCTION DE FERRO-ALLIAGES ET AUTRES PRODUITS NON CECA.<p></p><p></p>   CODE N.A.F 27.3 J <p></p><p></p>   Sont visées dans cette classe les activités de production de ferro-alliages au four électrique ou par aluminothermie, de l'électrométallurgie et de l'électrochimie associées.<p></p><p></p><p></p>   PRODUCTION D'ALUMINIUM.<p></p><p></p>   CODE N.A.F 27.4 C <p></p><p></p>   Sont visées dans cette classe les activités de production d'alumine et de production par électrolyse d'aluminium et d'alliages d'aluminium primaires.<p></p><p></p><p></p>   METALLURGIE DES AUTRES METAUX NON FERREUX.<p></p><p></p>   CODE N.A.F 27.4 M <p></p><p></p>   Sont visées dans ces classes les activités de production de magnésium et autres métaux légers par électrométallurgie, de l'électrométallurgie et de l'électrochimie associées.<p></p><p></p><p></p>   FABRICATION DE MATERIELS ELECTRIQUES N.C.A.<p></p><p></p>   CODE N.A.F 31.6 D <p></p> Est visée dans cette classe l'activité de fabrication d'électrodes en charbon ou en graphite.<p></p><p></p><p></p>   b) Peintures, encres, couleurs, colles et adhésifs (fédération des industries).<p></p><p></p><p></p>   FABRICATION DE PEINTURES ET VERNIS.<p></p><p></p>   CODE N.A.F 24.3 Z <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE COLLES ET GELATINES.<p></p><p></p>   CODE N.A.F 24.6 C <p></p> Sont visées toutes les activités comprises dans cette classe.<p></p><p></p><p></p>   c) Parfumerie (Fédération des industries de la).<p></p><p></p><p></p>   FABRICATION DE PARFUMS ET DE PRODUITS POUR LA TOILETTE.<p></p><p></p>   CODE N.A.F 24.5 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe.<p></p><p></p><p></p>   COMMERCE DE GROS DE PARFUMERIE ET DE PRODUITS DE BEAUTE.<p></p><p></p>   CODE N.A.F 51.4 L <p></p> Sont visés dans cette classe les établissements de commerce de gros dont l'activité s'exerce au profit d'autres unités, firmes ou sociétés, liées par le présent champ d'application, et exerçant en France ou à l'étranger, dès lors que ces autres unités, firmes ou sociétés font partie de la même entreprise, du même groupe, de la même unité économique et sociale, ou du même groupement d'intérêt économique que l'établissement concerné.<p></p><p></p><p></p>   d) Corps gras (Fédération nationale des industries de).<p></p><p></p><p></p>   PRODUCTION DE VIANDES DE BOUCHERIE.<p></p><p></p>   CODE N.A.F 15.1 A <p></p><p></p>   Sont visées dans cette classe les activités de :<p></p><p></p>   - fonte de saindoux et des graisses similaires ;<p></p><p></p>   - transformation des déchets d'abattage et production de farine de viandes ou d'os.<p></p><p></p><p></p>   FABRICATION D'HUILES ET GRAISSES BRUTES.<p></p><p></p>   CODE N.A.F 15.4 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION D'HUILES ET GRAISSES RAFFINEES.<p></p><p></p>   CODE N.A.F 15.4 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE MARGARINES.<p></p><p></p>   CODE N.A.F 15.4 E <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE SAVONS, DETERGENTS ET PRODUITS D'ENTRETIEN.<p></p><p></p>   CODE N.A.F 24.5 A <p></p><p></p>   Sont visées dans cette classe les activités de fabrication de savons, de fabrication de préparations détergentes ou adoucissantes pour la lessive, la vaisselle, etc.<p></p><p></p><p></p>   AUTRES ACTIVITES MANUFACTURIERES N.C.A.<p></p><p></p>   CODE N.A.F 36.6 E <p></p> Est visée dans ce groupe l'activité de fabrication de bougies et de chandelles.<p></p><p></p><p></p>   e) Enducteurs, calandreurs et fabricants de revêtements de sols et murs (syndicat des).<p></p><p></p><p></p>   INDUSTRIES TEXTILES N.C.A.<p></p><p></p>   CODE N.A.F 17.5 G <p></p> Est visée dans cette classe l'enduction d'étoffe. <p></p><p></p>   f) Papier (Comité compétent de la chambre syndicale du...).<p></p><p></p><p></p>   FABRICATION D'ARTICLES DE PAPETERIE.<p></p><p></p>   CODE N.A.F 21.2 G <p></p><p></p>   Est visée dans ce groupe l'activité de fabrication de stencils et de papier carbone.<p></p><p></p><p></p>   FABRICATION D'AUTRES ARTICLES EN PAPIER OU EN CARTON.<p></p><p></p>   CODE N.A.F 21.2 L <p></p> Est visée dans ce groupe la fabrication de consommables pour bureautique.<p></p><p></p><p></p>   g) Travaux photographiques (Syndicat des entrepreneurs de...).<p></p><p></p><p></p>   LABORATOIRES TECHNIQUES DE DéVELOPPEMENT ET DE TIRAGE.<p></p><p></p>   CODE N.A.F 74.8 B<p></p> Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   h) Reraffinage (chambre syndicale du...).<p></p><p></p><p></p>   RECUPERATION DE MATIERES NON METALLIQUES RECYCLABLES.<p></p><p></p>   CODE N.A.F 37.2 Z <p></p> Est visée dans ce groupe l'activité de régénération d'huiles usagées. <p></p>III. - AUTRES ACTIVITES COUVERTES PAR L'U.I.C OU PAR UN SYNDICAT PATRONAL ASSOCIE<p></p> 1) Centres et laboratoires<p></p><p></p><p></p>   RECHERCHE-DEVELOPPEMENT EN SCIENCES PHYSIQUES ET NATURELLES.<p></p><p></p>   CODE N.A.F 73.1 Z <p></p><p></p>   Sont visés dans cette classe les centres et laboratoires chimiques.<p></p><p></p><p></p>   INGENIERIE, ETUDES TECHNIQUES.<p></p><p></p>   CODE N.A.F 74.2 C <p></p><p></p>   Sont visés dans cette classe les centres et laboratoires chimiques.<p></p><p></p><p></p>   ANALYSES, ESSAIS ET INSPECTIONS TECHNIQUES.<p></p><p></p>   CODE N.A.F 74.3 B <p></p> Sont visés dans cette classe les centres et laboratoires chimiques.<p></p><p></p>2) Services<p></p><p></p>   Dans les classes ci-dessous est visé tout établissement :<p></p><p></p>   - qui réalise plus de la moitié de son activité au profit d'une ou plusieurs sociétés relevant du présent champ d'application et qui dépend juridiquement de cette ou de ces sociétés ;<p></p><p></p>   ou<p></p><p></p>   - qui réalise plus de la moitié de son activité au profit d'une ou plusieurs sociétés relevant du présent champ d'application dès lors que cette ou ces sociétés dépendent juridiquement de la même entreprise ou du même groupe ou du même groupement d'intérêt économique que l'établissement considéré.<p></p><p></p><p></p>   Transports par conduites ; N.A.F 60.3 Z <p></p><p></p>   Entreposage non frigorifique; N.A.F 63.1 E <p></p><p></p>   Conseil en systèmes informatiques; N.A.F 72.1 Z <p></p><p></p>   Réalisations de logiciels; N.A.F 72.2 Z <p></p><p></p>   Traitement de données; N.A.F 72.3 Z <p></p><p></p>   Autres activités rattachées à l'informatique; N.A.F 72.6 Z <p></p><p></p>   Activités comptables; N.A.F 74.1 C <p></p><p></p>   Conseil pour les affaires et la gestion; N.A.F 74.1 G <p></p><p></p>   Administration d'entreprises; N.A.F 74.1 J <p></p> Services annexes à la production; N.A.F 74.8 K <p></p><p></p>3) Formation professionnelle<p></p><p></p><p></p>   Enseignement secondaire technique ou professionnel; N.A.F 80.2 C <p></p><p></p>   Enseignement supérieur; N.A.F 80.3 Z <p></p><p></p>   Formation des adultes et formation continue; N.A.F 80.4 C <p></p> Autres enseignements; N.A.F 80.4 D <p></p><p></p>   Sont visés dans ces classes les organismes privés de formation qui remplissent les conditions suivantes :<p></p><p></p>   - les associations de formation créées à l'initiative d'organisations professionnelles d'employeurs et/ou d'entreprises relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application ou gérées par elles ;<p></p><p></p>   - les organismes dispensateurs de formation non dotés de la personnalité morale et intégrés à une entreprise relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application, ainsi que les organismes dispensateurs de formation dotés de la personnalité morale et dont l'activité s'exerce principalement au profit de l'entreprise qui a été à l'initiative de leur création, ou du groupe auquel appartient cette entreprise, dès lors que cette entreprise relève des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application ;<p></p><p></p>   - les centres de formation d'apprentis créés à l'initiative d'organisations professionnelles d'employeurs et/ou d'entreprises relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application.<p></p><p></p>4) Organisations professionnelles<p></p><p></p><p></p>   Organisations patronales et consulaires; N.A.F 91.1 A <p></p> Organisations professionnelles; N.A.F 91.1 C <p></p><p></p>   Sont visées dans ces classes les chambres syndicales professionnelles, fédérations, unions de syndicats professionnels dont l'activité s'exerce à titre principal au profit des établissements relevant des paragraphes I et II du présent champ d'application.<p></p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "3.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": "Modifié par Accord du 4 novembre 1996 en vigueur le lendemain de la parution du Journal officiel BO Conventions collectives 96-50.",
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                },
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846010",
                  "cid": "KALIARTI000005846007",
                  "intOrdre": 171796,
                  "etat": "MODIFIE",
                  "num": "1",
                  "path": "/KALISCTA000005722130/KALISCTA000005751407/KALIARTI000005846010",
                  "pathTitle": [
                    "Clauses générales",
                    "Objet de la convention - Champ d'application"
                  ],
                  "content": "Article 1er<p></p><p></p>   Le champ d'application professionnel de la convention collective nationale et des accords collectifs des industries chimiques est modifié comme suit :<p></p><p></p>   Le champ d'application de la convention collective nationale et des accords collectifs des industries chimiques est défini par référence à la nomenclature d'activités française instituée par le décret n° 92-1129 du 2 octobre 1992 et entrée en vigueur le 1er janvier 1993.<p></p><p></p>   Entrent dans le présent champ d'application :<p></p><p></p>   1. Les établissements et leurs annexes dont l'activité principale relève des classes énumérées ci-dessous ainsi que les holdings et sièges sociaux dont ils dépendent, sous réserve de dispositions particulières prévues dans certaines classes, notamment celles figurant au paragraphe III.<p></p><p></p>   2. Les établissements de commerce de gros dont l'activité principale porte sur la manipulation et la vente de produits dont la fabrication est visée par la nomenclature ci-dessous - notamment ceux qui relèvent de la classe 51.5 L - sous réserve des précisions apportées pour la classe 51.4 L et à l'exclusion des grossistes des corps gras.<p></p><p></p>I. - ACTIVITES COUVERTES PAR L'U.I.C.<p></p><p></p><p></p>   FABRICATION DE PRODUITS AMYLACES<p></p><p></p>   CODE N.A.F 15.6 D<p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion des amidonneries de blé, de riz et de manioc.<p></p><p></p><p></p>   INDUSTRIES ALIMENTAIRES N.C.A<p></p><p></p>   CODE N.A.F. 15.8 V <p></p><p></p>   Est visée dans cette classe l'activité de fabrication d'additifs et épaississants alimentaires. <p></p><p></p><p></p>   PRODUCTION D'ALCOOL ETHYLIQUE DE FERMENTATION ;<p></p><p></p>   CODE N.A.F 15.9 D <p></p><p></p>   Est visée dans cette classe l'activité de dénaturation d'alcool éthylique destiné à l'industrie chimique.<p></p><p></p><p></p>   COKEFACTION ;<p></p><p></p>   CODE N.A.F 23.1 Z <p></p><p></p>   Est visée dans cette classe l'activité de production de goudrons. <p></p><p></p>   ELABORATION ET TRANSFORMATION DE MATIERES NUCLEAIRES<p></p><p></p>   CODE N.A.F 23.3 Z <p></p><p></p>   Est visée dans cette classe l'activité de conversion du minerai d'uranium en hexafluorure.<p></p><p></p><p></p>   FABRICATION DE GAZ INDUSTRIELS.<p></p><p></p>   CODE N.A.F 24.1 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE COLORANTS ET DE PIGMENTS.<p></p><p></p>   CODE N.A.F 24.1 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION D'AUTRES PRODUITS CHIMIQUES INORGANIQUES DE BASE.<p></p><p></p>   Sont visées toutes les activités comprises dans cette classe.    CODE N.A.F 24.1 E <p></p><p></p>    FABRICATION D'AUTRES PRODUITS CHIMIQUES ORGANIQUES DE BASE.<p></p><p></p>   CODE N.A.F 24.1 G <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la production de charbon de bois à usage domestique non liée à la valorisation des jus pyroligneux.<p></p><p></p><p></p>   FABRICATION DE PRODUITS AZOTES ET D'ENGRAIS.<p></p><p></p>   CODE N.A.F 24.1 J <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE MATIERES PLASTIQUES DE BASE.<p></p><p></p>   CODE N.A.F 24.1 L <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la préparation de mélanges de matières plastiques de base, colorées ou non.<p></p><p></p>   Toutefois, les établissements ou entreprises relevant de cette dernière activité et qui, à la date d'entrée en vigueur du présent accord, appliquent le dispositif conventionnel de la chimie pourront continuer à l'appliquer.<p></p><p></p><p></p>   FABRICATION DE CAOUTCHOUC SYNTHETIQUE.<p></p><p></p>   CODE N.A.F 24.1 N <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE PRODUITS AGROCHIMIQUES.<p></p><p></p>   CODE N.A.F 24.2 Z <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE PRODUITS PHARMACEUTIQUES DE BASE.<p></p><p></p>   CODE N.A.F 24.4 A <p></p><p></p>   Sont visées dans cette classe toutes les activités d'études, de développement et de fabrication de produits chimiques et biochimiques de base à usage pharmaceutique ou des intermédiaires pour leur synthèse, à l'exclusion de la transformation du sang humain et de la fabrication de ses dérivés.<p></p><p></p><p></p>   FABRICATION DE SAVONS, DETERGENTS ET PRODUITS D'ENTRETIEN.<p></p><p></p>   CODE N.A.F 24.5 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la fabrication de savons et de la fabrication de préparations détergentes ou adoucissantes pour la lessive, la vaisselle, etc. qui sont visées dans le paragraphe II du présent champ d'application.<p></p><p></p><p></p>   FABRICATION DE PRODUITS EXPLOSIFS.<p></p><p></p>   CODE N.A.F 24.6 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION D'HUILES ESSENTIELLES.<p></p><p></p>   CODE N.A.F 24.6 E <p></p> Sont visées toutes les activités comprises dans cette classe.<p></p><p></p>    FABRICATION DE PRODUITS CHIMIQUES POUR LA PHOTOGRAPHIE.<p></p><p></p>   CODE N.A.F 24.6 G <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe hors la fabrication de papiers héliographiques.<p></p><p></p><p></p>   FABRICATION DE SUPPORTS DE DONNEES.<p></p><p></p>   CODE N.A.F 24.6 J <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. Toutefois, les établissements concernés qui, à la date d'entrée en vigueur du présent accord, ont sans discontinuer appliqué le dispositif conventionnel de la métallurgie pourront continuer à l'appliquer.<p></p><p></p><p></p>   FABRICATION DE PRODUITS CHIMIQUES à USAGE INDUSTRIEL.<p></p><p></p>   CODE N.A.F 24.6 L <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, y compris :<p></p><p></p>   - la fabrication de carburants et de lubrifiants de synthèse ;<p></p><p></p>   - le traitement des schistes bitumineux.<p></p><p></p><p></p>   FABRICATION DE PRODUITS ABRASIFS.<p></p><p></p>   CODE N.A.F 26.8 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe à l'exception de la production en pierres naturelles de meules et articles similaires.<p></p><p></p><p></p>   FABRICATION DE PRODUITS MINERAUX NON METALLIQUES N.C.A.<p></p><p></p>   CODE N.A.F 26.8 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe, à l'exception, d'une part, de la fabrication de garnitures de friction et de pièces pour les garnitures, d'autre part, de la fabrication d'argile expansée et de la fabrication de laine de roche.<p></p><p></p><p></p>   AUTRES ACTIVITES MANUFACTURIERES N.C.A.<p></p><p></p>   CODE N.A.F 36.6 E <p></p><p></p>   Sont visées dans cette classe :<p></p><p></p>   - les activités de fabrication d'allumettes ;<p></p><p></p>   - les activités de fabrication de crayons de couleur, crayons de mine de plomb, de fusain ou charbon ;<p></p><p></p>   - les activités de fabrication de craies à écrire, à dessiner, craies pour tailleur ;<p></p><p></p>   - les activités de fabrication de rubans pour machines à écrire ;<p></p><p></p>   - les activités de fabrication de tampons encreurs, dateurs et articles similaires sous condition qu'ils ne soient pas en métal.<p></p><p></p>    RECUPERATION DE MATIERES NON METALLIQUES RECYCLABLES.<p></p><p></p>   CODE N.A.F 37.2 Z <p></p><p></p>   Est visée dans cette classe l'activité de régénération ou de traitement physico-chimique à partir de la récupération de produits chimiques.<p></p><p></p><p></p>   COMMERCE DE GROS COMBUSTIBLES.<p></p><p></p>   CODE N.A.F 51.5 A <p></p><p></p>   Sont visées dans ce groupe les entreprises de commerce de gros de produits pétroliers qui, avant le 8 août 1990, appliquaient la convention collective nationale des industries chimiques.<p></p><p></p><p></p>   ELIMINATION ET TRAITEMENT DES AUTRES DECHETS.<p></p><p></p>   CODE N.A.F 90.0 C <p></p><p></p>   Sont visés dans cette classe les établissements dont l'activité principale a trait au traitement et à l'élimination des déchets industriels spéciaux.<p></p><p></p>   Cette classe comprend en particulier :<p></p><p></p>   - le traitement thermique ou physico-chimique de déchets industriels spéciaux ;<p></p><p></p>   - le traitement de déchets toxiques ;<p></p><p></p>   - le traitement de déchets et terres polluées résultant du traitement de sols pollués ;<p></p><p></p>   - la gestion des centres techniques d'enfouissement de déchets dangereux, y compris le stockage souterrain de ces déchets.<p></p><p></p>   Ne sont pas visées dans cette classe les activités de traitement thermique des déchets d'activités de soins.<p></p><p></p>II. - ACTIVITES COUVERTES PAR UN SYNDICAT PATRONAL ASSOCIE<p></p><p></p>   a) Electrométallurgiques, électrochimiques et connexes (Fédération nationale des industries).<p></p><p></p><p></p>   FABRICATION DE PRODUITS MINERAUX NON METALLIQUES N.C.A.<p></p><p></p>   CODE N.A.F 26.8 C <p></p><p></p>   Sont visées dans cette classe les activités de :<p></p><p></p>   - fabrication de corindon ;<p></p><p></p>   - fabrication d'articles en graphite et carbone.<p></p><p></p><p></p>   PRODUCTION DE FERRO-ALLIAGES ET AUTRES PRODUITS NON CECA.<p></p><p></p>   CODE N.A.F 27.3 J <p></p><p></p>   Sont visées dans cette classe les activités de production de ferro-alliages au four électrique ou par aluminothermie, de l'électrométallurgie et de l'électrochimie associées.<p></p><p></p><p></p>   PRODUCTION D'ALUMINIUM.<p></p><p></p>   CODE N.A.F 27.4 C <p></p><p></p>   Sont visées dans cette classe les activités de production d'alumine et de production par électrolyse d'aluminium et d'alliages d'aluminium primaires.<p></p><p></p><p></p>   METALLURGIE DES AUTRES METAUX NON FERREUX.<p></p><p></p>   CODE N.A.F 27.4 M <p></p><p></p>   Sont visées dans ces classes les activités de production de magnésium et autres métaux légers par électrométallurgie, de l'électrométallurgie et de l'électrochimie associées.<p></p><p></p><p></p>   FABRICATION DE MATERIELS ELECTRIQUES N.C.A.<p></p><p></p>   CODE N.A.F 31.6 D <p></p> Est visée dans cette classe l'activité de fabrication d'électrodes en charbon ou en graphite.<p></p><p></p><p></p>   b) Peintures, encres, couleurs, colles et adhésifs (fédération des industries).<p></p><p></p><p></p>   FABRICATION DE PEINTURES ET VERNIS.<p></p><p></p>   CODE N.A.F 24.3 Z <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE COLLES ET GELATINES.<p></p><p></p>   CODE N.A.F 24.6 C <p></p><p></p>   Sont visées dans cette classe les activités de fabrication de colles et de gélatines.<p></p><p></p>   Toutefois, les établissements concernés qui, à la date d'entrée en vigueur du présent accord, appliquaient le dispositif conventionnel du caoutchouc pourront continuer à l'appliquer.<p></p><p></p><p></p>   c) Parfumerie (Fédération des industries de la).<p></p><p></p><p></p>   FABRICATION DE PARFUMS ET DE PRODUITS POUR LA TOILETTE.<p></p><p></p>   CODE N.A.F 24.5 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe.<p></p><p></p><p></p>   COMMERCE DE GROS DE PARFUMERIE ET DE PRODUITS DE BEAUTE.<p></p><p></p>   CODE N.A.F 51.4 L <p></p> Sont visés dans cette classe les établissements de commerce de gros dont l'activité s'exerce au profit d'autres unités, firmes ou sociétés, liées par le présent champ d'application, et exerçant en France ou à l'étranger, dès lors que ces autres unités, firmes ou sociétés font partie de la même entreprise, du même groupe, de la même unité économique et sociale, ou du même groupement d'intérêt économique que l'établissement concerné.<p></p><p></p><p></p>   d) Corps gras (Fédération nationale des industries de).<p></p><p></p><p></p>   PRODUCTION DE VIANDES DE BOUCHERIE.<p></p><p></p>   CODE N.A.F 15.1 A <p></p><p></p>   Sont visées dans cette classe les activités de :<p></p><p></p>   - fonte de saindoux et des graisses similaires.<p></p><p></p><p></p>   FABRICATION D'HUILES ET GRAISSES BRUTES.<p></p><p></p>   CODE N.A.F 15.4 A <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION D'HUILES ET GRAISSES RAFFINEES.<p></p><p></p>   CODE N.A.F 15.4 C <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE MARGARINES.<p></p><p></p>   CODE N.A.F 15.4 E <p></p><p></p>   Sont visées toutes les activités comprises dans cette classe. <p></p><p></p>   FABRICATION DE SAVONS, DETERGENTS ET PRODUITS D'ENTRETIEN.<p></p><p></p>   CODE N.A.F 24.5 A <p></p><p></p>   Sont visées dans cette classe les activités de fabrication de savons, de fabrication de préparations détergentes ou adoucissantes pour la lessive, la vaisselle, etc.<p></p><p></p><p></p>   AUTRES ACTIVITES MANUFACTURIERES N.C.A.<p></p><p></p>   CODE N.A.F 36.6 E <p></p> Est visée dans ce groupe l'activité de fabrication de bougies et de chandelles.<p></p><p></p><p></p>   e) Enducteurs, calandreurs et fabricants de revêtements de sols et murs (syndicat des).<p></p><p></p><p></p>   INDUSTRIES TEXTILES N.C.A.<p></p><p></p>   CODE N.A.F 17.5 G <p></p> Est visée dans cette classe l'enduction d'étoffe. <p></p><p></p>   f) Papier (Comité compétent de la chambre syndicale du...).<p></p><p></p><p></p>   FABRICATION D'ARTICLES DE PAPETERIE.<p></p><p></p>   CODE N.A.F 21.2 G <p></p><p></p>   Est visée dans ce groupe l'activité de fabrication de stencils et de papier carbone.<p></p><p></p><p></p>   FABRICATION D'ARTICLES DE PAPETERIE.<p></p><p></p>   CODE N.A.F 21.2 L <p></p><p></p>   Sont visées dans cette classe les activités de fabrication de consommables pour bureautique à l'exception des papiers cartons.<p></p><p></p><p></p>   g) Travaux photographiques (Syndicat des entrepreneurs de...).<p></p><p></p><p></p>   LABORATOIRES TECHNIQUES DE DéVELOPPEMENT ET DE TIRAGE.<p></p><p></p>   CODE N.A.F 74.8 B<p></p><p></p>   Sont visés exclusivement dans cette classe les laboratoires photographiques de façonnage et les laboratoires cinématographiques.<p></p><p></p><p></p>   h) Reraffinage (chambre syndicale du ...).<p></p><p></p><p></p>   RECUPERATION DE MATIERES NON METALLIQUES RECYCLABLES.<p></p><p></p>   CODE N.A.F 37.2 Z <p></p> Est visée dans ce groupe l'activité de régénération d'huiles usagées. <p></p>III. - AUTRES ACTIVITES COUVERTES PAR L'U.I.C OU PAR UN SYNDICAT PATRONAL ASSOCIE<p></p> 1) Centres et laboratoires<p></p><p></p><p></p>   RECHERCHE-DEVELOPPEMENT EN SCIENCES PHYSIQUES ET NATURELLES.<p></p><p></p>   CODE N.A.F 73.1 Z <p></p><p></p>   Sont visés dans cette classe les centres et laboratoires chimiques.<p></p><p></p><p></p>   INGENIERIE, ETUDES TECHNIQUES.<p></p><p></p>   CODE N.A.F 74.2 C <p></p><p></p>   Sont visés dans cette classe les centres et laboratoires de recherche chimique.<p></p><p></p><p></p>   ANALYSES, ESSAIS ET INSPECTIONS TECHNIQUES.<p></p><p></p>   CODE N.A.F 74.3 B <p></p> Sont visés dans cette classe les centres et laboratoires de recherche chimiques.<p></p><p></p>   74.3 B. Analyses, essais et inspections techniques<p></p><p></p>   Sont visés dans cette classe les centres et laboratoires de recherche chimique.<p></p><p></p>2) Services<p></p><p></p>   Dans les classes ci-dessous sont visés les entreprises ou établissements qui, à la date de signature du présent accord, appliquent la convention collective nationale des industries chimiques.<p></p><p></p>   60.3 Z. Transports par conduites<p></p><p></p>   63.1 E. Entreposage non frigorifique<p></p><p></p>   72.1 Z. Conseil en systèmes informatiques<p></p><p></p>   72.2 Z. Réalisation de logiciels<p></p><p></p>   72.3 Z. Traitements de données<p></p><p></p>   72.6 Z. Autres activités rattachées à l'informatique<p></p><p></p>   74.1 C. Activités comptables<p></p><p></p>   74.1 G. Conseils pour les affaires et la gestion<p></p><p></p>   74.1 J. Administration d'entreprises<p></p><p></p>   74.8 K. Services annexes à la production<p></p><p></p>3) Formation professionnelle<p></p><p></p><p></p>   Enseignement secondaire technique ou professionnel; N.A.F 80.2 C <p></p><p></p>   Enseignement supérieur; N.A.F 80.3 Z <p></p><p></p>   Formation des adultes et formation continue; N.A.F 80.4 C <p></p> Autres enseignements; N.A.F 80.4 D <p></p><p></p>   Sont visés dans ces classes les organismes privés de formation qui remplissent les conditions suivantes :<p></p><p></p>   - les associations de formation créées à l'initiative d'organisations professionnelles d'employeurs et/ou d'entreprises relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application ou gérées par elles ;<p></p><p></p>   - les organismes dispensateurs de formation non dotés de la personnalité morale et intégrés à une entreprise relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application, ainsi que les organismes dispensateurs de formation dotés de la personnalité morale et dont l'activité s'exerce principalement au profit de l'entreprise qui a été à l'initiative de leur création, ou du groupe auquel appartient cette entreprise, dès lors que cette entreprise relève des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application ;<p></p><p></p>   - les centres de formation d'apprentis créés à l'initiative d'organisations professionnelles d'employeurs et/ou d'entreprises relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application.<p></p><p></p>4) Organisations professionnelles<p></p><p></p><p></p>   Organisations patronales et consulaires; N.A.F 91.1 A <p></p> Organisations professionnelles; N.A.F 91.1 C <p></p><p></p>   Sont visées dans ces classes les chambres syndicales professionnelles, fédérations, unions de syndicats professionnels dont l'activité s'exerce à titre principal au profit des établissements relevant des paragraphes I et II du présent champ d'application.<p></p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "4.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Accord 1996-11-04 en vigueur le lendemain de la parution du Journal officiel, BO Conventions collectives 96-50",
                      "linkType": "MODIFICATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    },
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": "Modifié par Avenant du 12 novembre 1997 en vigueur le lendemain de la parution du Journal officiel, BO conventions collectives 98-3.",
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                },
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846011",
                  "cid": "KALIARTI000005846007",
                  "intOrdre": 214745,
                  "etat": "VIGUEUR_NON_ETEN",
                  "num": "1er",
                  "path": "/KALISCTA000005722130/KALISCTA000005751407/KALIARTI000005846011",
                  "pathTitle": [
                    "Clauses générales",
                    "Objet de la convention - Champ d'application"
                  ],
                  "content": "<p>Le champ d'application professionnel de la convention collective nationale et des accords collectifs des industries chimiques est modifié comme suit :</p><p>Le champ d'application de la convention collective nationale et des accords collectifs des industries chimiques est défini par référence à la nomenclature d'activités française instituée par le décret n° 92-1129 du 2 octobre 1992 et entrée en vigueur le 1er janvier 1993.</p><p>Entrent dans le présent champ d'application :</p><p>1. Les établissements et leurs annexes dont l'activité principale relève des classes énumérées ci-dessous ainsi que les holdings et sièges sociaux dont ils dépendent, sous réserve de dispositions particulières prévues dans certaines classes, notamment celles figurant au paragraphe III.</p><p>2. Les établissements de commerce de gros dont l'activité principale porte sur la manipulation et la vente de produits dont la fabrication est visée par la nomenclature ci-dessous - notamment ceux qui relèvent de la classe 51.5 L - sous réserve des précisions apportées pour la classe 51.4 L et à l'exclusion des grossistes des corps gras.</p><p>I. - ACTIVITES COUVERTES PAR L'UIC</p><p>FABRICATION DE PRODUITS AMYLACES</p><p>CODE NAF 15.6 D</p><p>Sont visées toutes les activités comprises dans cette classe, à l'exclusion des amidonneries de blé, de riz et de manioc.</p><p>INDUSTRIES ALIMENTAIRES NCA</p><p>CODE NAF 15.8 V </p><p>Est visée dans cette classe l'activité de fabrication d'additifs et épaississants alimentaires. </p><p>PRODUCTION D'ALCOOL ETHYLIQUE DE FERMENTATION ;</p><p>CODE NAF 15.9 D </p><p>Est visée dans cette classe l'activité de dénaturation d'alcool éthylique destiné à l'industrie chimique.</p><p>COKEFACTION ;</p><p>CODE NAF 23.1 Z </p><p>Est visée dans cette classe l'activité de production de goudrons. </p><p>ELABORATION ET TRANSFORMATION DE MATIERES NUCLEAIRES</p><p>CODE NAF 23.3 Z </p><p>Est visée dans cette classe l'activité de conversion du minerai d'uranium en hexafluorure.</p><p>FABRICATION DE GAZ INDUSTRIELS.</p><p>CODE NAF 24.1 A </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE COLORANTS ET DE PIGMENTS.</p><p>CODE N.A.F 24.1 C </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION D'AUTRES PRODUITS CHIMIQUES INORGANIQUES DE BASE.</p><p>Sont visées toutes les activités comprises dans cette classe. CODE NAF 24.1 E </p><p>FABRICATION D'AUTRES PRODUITS CHIMIQUES ORGANIQUES DE BASE.</p><p>CODE NAF 24.1 G </p><p>Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la production de charbon de bois à usage domestique non liée à la valorisation des jus pyroligneux.</p><p>FABRICATION DE PRODUITS AZOTES ET D'ENGRAIS.</p><p>CODE NAF 24.1 J </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE MATIERES PLASTIQUES DE BASE.</p><p>CODE NAF 24.1 L </p><p>Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la préparation de mélanges de matières plastiques de base, colorées ou non.</p><p>Toutefois, les établissements ou entreprises relevant de cette dernière activité et qui, à la date d'entrée en vigueur du présent accord, appliquent le dispositif conventionnel de la chimie pourront continuer à l'appliquer.</p><p>FABRICATION DE CAOUTCHOUC SYNTHETIQUE.</p><p>CODE NAF 24.1 N </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE PRODUITS AGROCHIMIQUES.</p><p>CODE NAF 24.2 Z </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE PRODUITS PHARMACEUTIQUES DE BASE.</p><p>CODE NAF 24.4 A </p><p>Sont visées dans cette classe toutes les activités d'études, de développement et de fabrication de produits chimiques et biochimiques de base à usage pharmaceutique ou des intermédiaires pour leur synthèse, à l'exclusion de la transformation du sang humain et de la fabrication de ses dérivés.</p><p>FABRICATION DE SAVONS, DETERGENTS ET PRODUITS D'ENTRETIEN.</p><p>CODE NAF 24.5 A </p><p>Sont visées toutes les activités comprises dans cette classe, à l'exclusion de la fabrication de savons et de la fabrication de préparations détergentes ou adoucissantes pour la lessive, la vaisselle, etc. qui sont visées dans le paragraphe II du présent champ d'application.</p><p>FABRICATION DE PRODUITS EXPLOSIFS.</p><p>CODE NAF 24.6 A </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION D'HUILES ESSENTIELLES.</p><p>CODE NAF 24.6 E </p><p>Sont visées toutes les activités comprises dans cette classe.</p><p>FABRICATION DE PRODUITS CHIMIQUES POUR LA PHOTOGRAPHIE.</p><p>CODE NAF 24.6 G </p><p>Sont visées toutes les activités comprises dans cette classe hors la fabrication de papiers héliographiques.</p><p>FABRICATION DE SUPPORTS DE DONNEES.</p><p>CODE NAF 24.6 J </p><p>Sont visées toutes les activités comprises dans cette classe. Toutefois, les établissements concernés qui, à la date d'entrée en vigueur du présent accord, ont sans discontinuer appliqué le dispositif conventionnel de la métallurgie pourront continuer à l'appliquer.</p><p>FABRICATION DE PRODUITS CHIMIQUES à USAGE INDUSTRIEL.</p><p>CODE NAF 24.6 L </p><p>Sont visées toutes les activités comprises dans cette classe, y compris :</p><p>- la fabrication de carburants et de lubrifiants de synthèse ;</p><p>- le traitement des schistes bitumineux.</p><p>FABRICATION DE PRODUITS ABRASIFS.</p><p>CODE NAF 26.8 A </p><p>Sont visées toutes les activités comprises dans cette classe à l'exception de la production en pierres naturelles de meules et articles similaires.</p><p>FABRICATION DE PRODUITS MINERAUX NON METALLIQUES N.C.A.</p><p>CODE NAF 26.8 C </p><p>Sont visées toutes les activités comprises dans cette classe, à l'exception, d'une part, de la fabrication de garnitures de friction et de pièces pour les garnitures, d'autre part, de la fabrication d'argile expansée et de la fabrication de laine de roche.</p><p>AUTRES ACTIVITES MANUFACTURIERES N.C.A.</p><p>CODE NAF 36.6 E </p><p>Sont visées dans cette classe :</p><p>- les activités de fabrication d'allumettes ;</p><p>- les activités de fabrication de crayons de couleur, crayons de mine de plomb, de fusain ou charbon ;</p><p>- les activités de fabrication de craies à écrire, à dessiner, craies pour tailleur ;</p><p>- les activités de fabrication de rubans pour machines à écrire ;</p><p>- les activités de fabrication de tampons encreurs, dateurs et articles similaires sous condition qu'ils ne soient pas en métal.</p><p>RECUPERATION DE MATIERES NON METALLIQUES RECYCLABLES.</p><p>CODE NAF 37.2 Z </p><p>Est visée dans cette classe l'activité de régénération ou de traitement physico-chimique à partir de la récupération de produits chimiques.</p><p>COMMERCE DE GROS COMBUSTIBLES.</p><p>CODE NAF 51.5 A </p><p>Sont visées dans ce groupe les entreprises de commerce de gros de produits pétroliers qui, avant le 8 août 1990, appliquaient la convention collective nationale des industries chimiques.</p><p>ELIMINATION ET TRAITEMENT DES AUTRES DECHETS.</p><p>CODE NAF 90.0 C </p><p>Sont visées, dante cette classe, les entreprises dont l'activité principale a trait au traitement et à l'élimination des déchets industriels spéciaux.</p><p>Cette classe comprend :</p><p>- le traitement thermique ou physico-chimique de déchets industriels spéciaux ;</p><p>- le traitement de déchets toxiques ;</p><p>- le traitement de déchets et terres polluées résultant du traitement de sols pollués ;</p><p>- le stockage souterrain de déchets.</p><p>Ne sont pas visées dans cette classe les activités de traitement thermique d'activités de soins.</p><p>Les entreprises exerçant à titre principal une activité visée ci-dessus qui, à la date de la signature du présent avenant, appliquent la convention collective nationale des activités du déchet, laquelle vise également les activités référencées à la classe 90.0C, peuvent continuer à l'appliquer.</p><p>Les entreprises exerçant à titre principal une activité visée ci-dessus qui ont été créées, se créeront ou développeront ladite activité après la date de signature du présent avenant devront choisir, après accord collectif ou à défaut après consultation des représentants du personnel, d'appliquer soit la convention collective nationale des activités du déchet, soit la présente convention.</p><p>Toutefois, lorsque un ou des établissements appartiennent ou viennent à appartenir majoritairement à une entreprise dont l'activité entre dans le champ d'application de la présente convention, celle-ci sera alors obligatoirement applicable.</p><p>II. - ACTIVITES COUVERTES PAR UN SYNDICAT PATRONAL ASSOCIE</p><p>a) Electrométallurgiques, électrochimiques et connexes (Fédération nationale des industries).</p><p>FABRICATION DE PRODUITS MINERAUX NON METALLIQUES N.C.A.</p><p>CODE NAF 26.8 C </p><p>Sont visées dans cette classe les activités de :</p><p>- fabrication de corindon ;</p><p>- fabrication d'articles en graphite et carbone.</p><p>PRODUCTION DE FERRO-ALLIAGES ET AUTRES PRODUITS NON CECA.</p><p>CODE NAF 27.3 J </p><p>Sont visées dans cette classe les activités de production de ferro-alliages au four électrique ou par aluminothermie, de l'électrométallurgie et de l'électrochimie associées.</p><p>PRODUCTION D'ALUMINIUM.</p><p>CODE NAF 27.4 C </p><p>Sont visées dans cette classe les activités de production d'alumine et de production par électrolyse d'aluminium et d'alliages d'aluminium primaires.</p><p>METALLURGIE DES AUTRES METAUX NON FERREUX.</p><p>CODE NAF 27.4 M </p><p>Sont visées dans ces classes les activités de production de magnésium et autres métaux légers par électrométallurgie, de l'électrométallurgie et de l'électrochimie associées.</p><p>FABRICATION DE MATERIELS ELECTRIQUES N.C.A.</p><p>CODE NAF 31.6 D </p><p>Est visée dans cette classe l'activité de fabrication d'électrodes en charbon ou en graphite.</p><p>b) Peintures, encres, couleurs, colles et adhésifs (fédération des industries).</p><p>FABRICATION DE PEINTURES ET VERNIS.</p><p>CODE NAF 24.3 Z </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE COLLES ET GELATINES.</p><p>CODE NAF 24.6 C </p><p>Sont visées dans cette classe les activités de fabrication de colles et de gélatines.</p><p>Toutefois, les établissements concernés qui, à la date d'entrée en vigueur du présent accord, appliquaient le dispositif conventionnel du caoutchouc pourront continuer à l'appliquer.</p><p>c) Parfumerie (Fédération des industries de la).</p><p>FABRICATION DE PARFUMS ET DE PRODUITS POUR LA TOILETTE.</p><p>CODE NAF 24.5 C </p><p>Sont visées toutes les activités comprises dans cette classe.</p><p>COMMERCE DE GROS DE PARFUMERIE ET DE PRODUITS DE BEAUTE.</p><p>CODE NAF 51.4 L </p><p>Sont visés dans cette classe les établissements de commerce de gros dont l'activité s'exerce au profit d'autres unités, firmes ou sociétés, liées par le présent champ d'application, et exerçant en France ou à l'étranger, dès lors que ces autres unités, firmes ou sociétés font partie de la même entreprise, du même groupe, de la même unité économique et sociale, ou du même groupement d'intérêt économique que l'établissement concerné.</p><p>d) Corps gras (Fédération nationale des industries de).</p><p>PRODUCTION DE VIANDES DE BOUCHERIE.</p><p>CODE NAF 15.1 A </p><p>Sont visées dans cette classe les activités de :</p><p>- fonte de saindoux et des graisses similaires.</p><p>FABRICATION D'HUILES ET GRAISSES BRUTES.</p><p>CODE NAF 15.4 A </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION D'HUILES ET GRAISSES RAFFINEES.</p><p>CODE NAF 15.4 C </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE MARGARINES.</p><p>CODE NAF 15.4 E </p><p>Sont visées toutes les activités comprises dans cette classe. </p><p>FABRICATION DE SAVONS, DETERGENTS ET PRODUITS D'ENTRETIEN.</p><p>CODE NAF 24.5 A </p><p>Sont visées dans cette classe les activités de fabrication de savons, de fabrication de préparations détergentes ou adoucissantes pour la lessive, la vaisselle, etc.</p><p>AUTRES ACTIVITES MANUFACTURIERES N.C.A.</p><p>CODE NAF 36.6 E </p><p>Est visée dans ce groupe l'activité de fabrication de bougies et de chandelles.</p><p>e) Enducteurs, calandreurs et fabricants de revêtements de sols et murs (syndicat des).</p><p>INDUSTRIES TEXTILES N.C.A.</p><p>CODE NAF 17.5 G </p><p>Est visée dans cette classe l'enduction d'étoffe. </p><p>f) Papier (Comité compétent de la chambre syndicale du...).</p><p>FABRICATION D'ARTICLES DE PAPETERIE.</p><p>CODE NAF 21.2 G </p><p>Est visée dans ce groupe l'activité de fabrication de stencils et de papier carbone.</p><p>FABRICATION D'ARTICLES DE PAPETERIE.</p><p>CODE NAF 21.2 L </p><p>Sont visées dans cette classe les activités de fabrication de consommables pour bureautique à l'exception des papiers cartons.</p><p>g) Travaux photographiques (Syndicat des entrepreneurs de...).</p><p>LABORATOIRES TECHNIQUES DE DéVELOPPEMENT ET DE TIRAGE.</p><p>CODE NAF 74.8 B</p><p>Sont visés exclusivement dans cette classe les laboratoires photographiques de façonnage et les laboratoires cinématographiques.</p><p>h) Reraffinage (chambre syndicale du ...).</p><p>RECUPERATION DE MATIERES NON METALLIQUES RECYCLABLES.</p><p>CODE NAF 37.2 Z </p><p>Est visée dans ce groupe l'activité de régénération d'huiles usagées. </p><p>III. - AUTRES ACTIVITES COUVERTES PAR L'U.I.C OU PAR UN SYNDICAT PATRONAL ASSOCIE</p><p>1) Centres et laboratoires</p><p>RECHERCHE-DEVELOPPEMENT EN SCIENCES PHYSIQUES ET NATURELLES.</p><p>CODE NAF 73.1 Z </p><p>Sont visés dans cette classe les centres et laboratoires chimiques.</p><p>INGENIERIE, ETUDES TECHNIQUES.</p><p>CODE NAF 74.2 C </p><p>Sont visés dans cette classe les centres et laboratoires de recherche chimique.</p><p>ANALYSES, ESSAIS ET INSPECTIONS TECHNIQUES.</p><p>CODE NAF 74.3 B </p><p>Sont visés dans cette classe les centres et laboratoires de recherche chimiques.</p><p>74.3 B. Analyses, essais et inspections techniques</p><p>Sont visés dans cette classe les centres et laboratoires de recherche chimique.</p><p>2) Services</p><p>Les établissements ou filiales de groupes chimiques qui ont une activité de services dans une des activités suivantes :</p><p>60.3. Z.</p><p>Transports par conduites</p><p>63.1. E.</p><p>Entreposage non frigorifique</p><p>72.1. Z.</p><p>Conseil en systèmes informatiques</p><p>72.2. Z.</p><p>Réalisation de logiciels</p><p>72.3. Z.</p><p>Traitement de données</p><p>72.6. Z.</p><p>Autres activités rattachées à l'informatique</p><p>74.1. C.</p><p>Activités comptables</p><p>74.1. G.</p><p>Conseils pour les affaires et la gestion</p><p>74.1. J.</p><p>Administration d'entreprises</p><p>74.8. K.</p><p>Services annexes à la production</p><p>et dont le personnel bénéficie déjà des dispositions de la convention collective nationale des industries chimiques pourront continuer de l'appliquer dès lors qu'ils réalisent au moins 66 % de leur chiffre d'affaires au profit de leurs groupes d'origine après accord collectif ou à défaut après consultation des représentants du personnel.</p><p>Les dispositions ci-dessus entreront en vigueur comme l'accord du 4 novembre 1996 le jour suivant la parution au Journal officiel de l'arrêté ministériel portant son extension.</p><p>Elles seront déposées à la direction départementale du travail, de l'emploi et de la formation professionnelle des Hauts-de-Seine, conformément aux dispositions de l'article L. 132-10 du code du travail.</p><p>3) Formation professionnelle</p><p>Enseignement secondaire technique ou professionnel; NAF 80.2 C </p><p>Enseignement supérieur; NAF 80.3 Z </p><p>Formation des adultes et formation continue; NAF 80.4 C </p><p>Autres enseignements; NAF 80.4 D </p><p>Sont visés dans ces classes les organismes privés de formation qui remplissent les conditions suivantes :</p><p>- les associations de formation créées à l'initiative d'organisations professionnelles d'employeurs et/ou d'entreprises relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application ou gérées par elles ;</p><p>- les organismes dispensateurs de formation non dotés de la personnalité morale et intégrés à une entreprise relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application, ainsi que les organismes dispensateurs de formation dotés de la personnalité morale et dont l'activité s'exerce principalement au profit de l'entreprise qui a été à l'initiative de leur création, ou du groupe auquel appartient cette entreprise, dès lors que cette entreprise relève des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application ;</p><p>- les centres de formation d'apprentis créés à l'initiative d'organisations professionnelles d'employeurs et/ou d'entreprises relevant des industries chimiques telles que définies aux paragraphes 1 et 11 du présent champ d'application.</p><p>4) Organisations professionnelles</p><p>Organisations patronales et consulaires; NAF 91.1 A </p><p>Organisations professionnelles; NAF 91.1 C </p><p>Sont visées dans ces classes les chambres syndicales professionnelles, fédérations, unions de syndicats professionnels dont l'activité s'exerce à titre principal au profit des établissements relevant des paragraphes I et II du présent champ d'application.</p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "5.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Accord 1996-11-04 en vigueur le lendemain de la parution du Journal officiel, BO Conventions collectives 96-50",
                      "linkType": "MODIFICATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    },
                    {
                      "textCid": "",
                      "textTitle": "Avenant 1997-11-12 en vigueur le lendemain de la parution du Journal officiel, BO conventions collectives 98-3",
                      "linkType": "MODIFICATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    },
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": "Modifié par Avenant du 7 mai 1999 BO conventions collectives 99-35.",
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                }
              ],
              "commentaire": null,
              "renvoi": "",
              "renvoiNum": ""
            },
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751408",
              "cid": "KALISCTA000005751408",
              "intOrdre": 85898,
              "etat": "VIGUEUR_ETEN",
              "title": "Durée de la convention - Dénonciation et révision",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846012",
                  "cid": "KALIARTI000005846012",
                  "intOrdre": 42949,
                  "etat": "VIGUEUR_ETEN",
                  "num": "2",
                  "path": "/KALISCTA000005722130/KALISCTA000005751408/KALIARTI000005846012",
                  "pathTitle": [
                    "Clauses générales",
                    "Durée de la convention - Dénonciation et révision"
                  ],
                  "content": "<p>1. La présente convention ne pourra être dénoncée avant l'expiration d'une période de 1 an à compter de la date de mise en application, celle-ci étant fixée au 30 décembre 1952. Elle se poursuivra ensuite par tacite reconduction pour deux périodes successives de 6 mois, puis pour une période indéterminée.</p><p>2. La dénonciation ou la demande de révision par l'une des parties contractantes devra être portée, par lettre recommandée avec accusé de réception, à la connaissance des autres parties contractantes.</p><p>3. La partie dénonçant la convention ou en demandant la révision partielle devra accompagner sa lettre de notification d'un projet de textes relatifs aux points sujets à révision. Les discussions devront commencer dans les 30 jours suivant la date d'envoi de la lettre de notification.</p><p>4. Qu'il s'agisse de dénonciation ou de révision, la présente convention restera en vigueur jusqu'à la date d'application des nouvelles dispositions.</p><p>5. Sauf accord mutuel, aucune demande de révision ne pourra être introduite dans les 6 mois suivant la mise en vigueur de la dernière révision.</p><p>Les dispositions du présent article ne peuvent faire obstacle à l'ouverture de discussions pour la mise en harmonie de la convention avec toute nouvelle prescription légale et ne s'appliquant pas aux questions de salaires.</p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": null,
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                }
              ],
              "commentaire": null,
              "renvoi": "",
              "renvoiNum": ""
            },
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751409",
              "cid": "KALISCTA000005751409",
              "intOrdre": 128847,
              "etat": "VIGUEUR_ETEN",
              "title": "Avenants régionaux et locaux",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846015",
                  "cid": "KALIARTI000005846015",
                  "intOrdre": 42949,
                  "etat": "VIGUEUR_ETEN",
                  "num": "3",
                  "path": "/KALISCTA000005722130/KALISCTA000005751409/KALIARTI000005846015",
                  "pathTitle": [
                    "Clauses générales",
                    "Avenants régionaux et locaux"
                  ],
                  "content": "<p></p>   Des avenants de branches d'industrie, des avenants régionaux ou locaux adapteront, si les parties intéressées en reconnaissent la nécessité, la présente convention ou certaines de ses dispositions aux conditions particulières de travail dans la branche d'industrie, la région ou la localité considérée, étant entendu que ces avenants ne pourront être moins favorables que la présente convention.<p></p><p></p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": null,
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                }
              ],
              "commentaire": null,
              "renvoi": "",
              "renvoiNum": ""
            },
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751410",
              "cid": "KALISCTA000005751410",
              "intOrdre": 171796,
              "etat": "VIGUEUR_ETEN",
              "title": "Avantages acquis",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846016",
                  "cid": "KALIARTI000005846016",
                  "intOrdre": 42949,
                  "etat": "VIGUEUR_ETEN",
                  "num": "4",
                  "path": "/KALISCTA000005722130/KALISCTA000005751410/KALIARTI000005846016",
                  "pathTitle": [
                    "Clauses générales",
                    "Avantages acquis"
                  ],
                  "content": "<p></p>   1. La présente convention ne peut être en aucun cas la cause de restriction aux avantages acquis antérieurement à la date de la signature de la présente convention par le salarié dans l'établissement qui l'emploie.<p></p><p></p>   2. Les clauses de la présente convention collective remplaceront celles de tous les contrats existants, y compris les contrats à durée déterminée, chaque fois que celles-ci seront moins avantageuses pour les salariés ou équivalentes.<p></p><p></p>   3. Les dispositions de la présente convention ne font pas obstacle au maintien des usages plus favorables reconnus dans certaines entreprises.<p></p><p></p>   Les avantages reconnus par la présente convention ne peuvent en aucun cas s'interpréter comme s'ajoutant aux avantages déjà accordés pour le même objet dans certaines entreprises à la suite d'usage ou de convention.<p></p><p></p>   4. Lorsqu'une convention collective régionale ou un accord régional actuellement en vigueur comporte des avantages particuliers à certaines fonctions, catégories ou emplois, des avenants régionaux ou locaux pris dans le cadre de la présente convention nationale préciseront les conditions d'application de ces avantages particuliers.<p></p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [],
                  "conditionDiffere": null,
                  "historique": null,
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                }
              ],
              "commentaire": null,
              "renvoi": "",
              "renvoiNum": ""
            },
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751411",
              "cid": "KALISCTA000005751411",
              "intOrdre": 214745,
              "etat": "VIGUEUR_ETEN",
              "title": "Dispositions concernant le libre exercice du droit syndical et la liberté d'opinion",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846017",
                  "cid": "KALIARTI000005846017",
                  "intOrdre": 42949,
                  "etat": "VIGUEUR_ETEN",
                  "num": "5",
                  "path": "/KALISCTA000005722130/KALISCTA000005751411/KALIARTI000005846017",
                  "pathTitle": [
                    "Clauses générales",
                    "Dispositions concernant le libre exercice du droit syndical et la liberté d'opinion"
                  ],
                  "content": "<p>1. Les parties contractantes reconnaissent à chacun la liberté d'opinion ainsi que celle d'adhérer ou non à un syndicat professionnel de son choix et la liberté pour les syndicats d'exercer leur action conformément à la loi.</p><p>2. Les parties s'engagent à ne prendre en aucun cas en considération pour quiconque dans les relations de travail au sein de l'entreprise : les origines, les croyances, les opinions ni le fait d'appartenir ou de ne pas appartenir à un syndicat.</p><p>Les employeurs s'engagent en particulier à ne pas prendre en considération le fait d'appartenir ou de ne pas appartenir à un syndicat pour arrêter leurs décisions en ce qui concerne l'embauchage, la conduite ou la répartition du travail, les mesures de discipline et de congédiement, la rétribution, l'avancement et la promotion.</p><p>3. Si l'une des parties contractantes conteste le motif d'un congédiement comme violant le droit syndical, les deux parties s'emploieront à reconnaître les faits et à faire apporter au cas litigieux une solution équitable consistant de préférence dans la réintégration du congédié dans son emploi. Cette disposition ne fait pas obstacle au droit pour l'intéressé de demander judiciairement réparation du préjudice qui lui aurait été causé.</p><p>4. Dans le cas où un salarié est appelé à quitter son emploi pour exercer une fonction syndicale élective, il jouira sur sa demande, présentée dans le mois suivant l'expiration de son mandat syndical, et ce pendant 6 mois, d'une priorité de réintégration dans son ancien emploi ou un emploi similaire avec les avantages y attachés. Les dispositions ci-dessus ne seront pas obligatoirement applicables à des mandats syndicaux successifs ou excédant 4 ans.</p><p>A sa réintégration, le salarié reprendra l'ancienneté et les droits y afférents qu'il avait au départ de l'entreprise.</p><p>La priorité ci-dessus cessera dans le cas où l'intéressé aura refusé la première offre de réintégration faite dans les conditions prévues ou n'aura pas répondu à celles-ci dans un délai de 1 mois.</p><p>A titre exceptionnel, en cas d'impossibilité de réintégration dans le délai prévu, l'intéressé recevra une indemnité égale à celle qu'il aurait reçue s'il avait été licencié au moment où il a quitté l'établissement pour exercer ses fonctions syndicales.</p><p>5. Dans les établissements employant habituellement au moins 150 salariés, lorsque l'effectif des salariés travaillant en service continu ou semi-continu est égal ou supérieur à 15 % de l'effectif total, le crédit d'heures mis à la disposition de chaque délégué syndical pour l'exercice de ses fonctions, tel qu'il est fixé par l'article L. 412-16 du code du travail, sera augmenté de 5 heures par mois.</p>",
                  "nota": null,
                  "comporteLiens": true,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [
                    {
                      "textCid": "",
                      "textTitle": "Code du travail L412-16",
                      "linkType": "CITATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "date": 1664565895216,
                      "parentCid": null,
                      "numTexte": "",
                      "datePubli": null,
                      "dateDebut": null
                    }
                  ],
                  "conditionDiffere": null,
                  "historique": "Modifié par Accord du 26 mars 1976 étendu par arrêté du 2 octobre 1978 JONC 26 octobre 1978",
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                }
              ],
              "commentaire": null,
              "renvoi": "",
              "renvoiNum": ""
            },
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751412",
              "cid": "KALISCTA000005751412",
              "intOrdre": 257694,
              "etat": "VIGUEUR_ETEN",
              "title": "Délégués du personnel",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846018",
                  "cid": "KALIARTI000005846018",
                  "intOrdre": 42949,
                  "etat": "VIGUEUR_ETEN",
                  "num": "6",
                  "path": "/KALISCTA000005722130/KALISCTA000005751412/KALIARTI000005846018",
                  "pathTitle": [
                    "Clauses générales",
                    "Délégués du personnel"
                  ],
                  "content": "<p>1. Le statut et la mission des délégués du personnel sont déterminés par la loi. Il est précisé que dans la définition de cette mission, les stipulations de la convention collective sont admises au même titre que les lois et règlements.</p><p>2. Sauf accord particulier, dans les établissements de plus de 250 salariés, il est institué 4 collèges électoraux et le personnel est réparti de la manière suivante entre ces collèges :</p><p>a) Ouvriers (groupes I, II et III) ;</p><p>b) Employés et techniciens (groupes I, II et III) ;</p><p>c) Agents de maîtrise et techniciens (groupe IV) ;</p><p>d) Ingénieurs et cadres (groupe V).</p><p>Le nombre des collèges est fixé à 3 dans les établissements de 101 à 250 salariés et à 2 dans les établissements de 11 à 100 salariés. Des accords prévoiront la répartition du personnel dans ces collèges.</p><p>3. Afin d'améliorer la représentation des différentes catégories de personnel et des principaux ateliers ou services, des accords d'établissement pourront prévoir une augmentation du nombre des délégués.</p><p>4. Dans les établissements comptant de 5 à 10 salariés, si les intéressés dans leur majorité le demandent, il sera procédé à l'élection d'un délégué titulaire et d'un délégué suppléant. Ces délégués auront le statut et les attributions définis par la loi, mais le temps alloué pour l'exercice de leurs fonctions sera de 5 heures par mois, sauf cas exceptionnels. Au cas où il n'y aurait pas de délégué, les salariés pourront se faire assister par un représentant d'un syndicat, ou d'une fédération de la profession, ou à défaut d'une union départementale ou locale, si une première réclamation directe n'avait pas reçu satisfaction.</p><p>5. Dans l'exercice de leur mandat et dans la limite du nombre d'heures qui leur est alloué, les délégués pourront, sur leur demande, s'absenter de l'établissement pour des motifs ayant trait à leurs fonctions sous réserve de ne pas apporter de gêne excessive à la production.</p><p>6. Les électeurs se trouvant dans l'impossibilité de se rendre au lieu de vote auront la faculté de voter par correspondance dans les conditions suivantes :</p><p>- ils feront parvenir au bureau de vote, avant la clôture du scrutin une enveloppe revêtue de leurs nom et signature et contenant l'enveloppe de vote qui renfermera la liste de leur choix. L'enveloppe extérieure ne pourra être ouverte que par le bureau de vote.</p><p>7. Dans les établissements où l'effectif des salariés travaillant en service continu ou semi-continu est égal ou supérieur à 15 % de l'effectif total, le crédit d'heures mis à la disposition de chaque délégué du personnel pour l'exercice de ses fonctions, tel qu'il est fixé par l'article L. 420-19 du code du travail, sera augmenté de 5 heures par mois.</p>",
                  "nota": null,
                  "comporteLiens": true,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,
                  "lstLienModification": [
                    {
                      "textCid": "",
                      "textTitle": "Accord 1976-03-26 étendu par arrêté du 2 octobre 1978 JONC 26 octobre 1978",
                      "linkType": "MODIFICATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    },
                    {
                      "textCid": "",
                      "textTitle": "Convention collective nationale 1952-12-30 étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
                      "linkType": "CREATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "datePubliTexte": null,
                      "dateSignaTexte": null,
                      "dateDebutCible": null
                    }
                  ],
                  "lstLienCitation": [
                    {
                      "textCid": "",
                      "textTitle": "Code du travail L420-19",
                      "linkType": "CITATION",
                      "linkOrientation": "source",
                      "articleNum": "",
                      "articleId": "",
                      "natureText": "",
                      "date": 1664565895394,
                      "parentCid": null,
                      "numTexte": "",
                      "datePubli": null,
                      "dateDebut": null
                    }
                  ],
                  "conditionDiffere": null,
                  "historique": "Modifié par Accord du 22 mai 1979 étendu par arrêté du 3 janvier 1992 JORF 11 janvier 1992",
                  "surtitre": null,
                  "renvoi": null,
                  "versionLabel": null
                }
              ],
              "commentaire": null,
              "renvoi": "",
              "renvoiNum": ""
            },
            {
              "executionTime": 0,
              "dereferenced": false,
              "id": "KALISCTA000005751413",
              "cid": "KALISCTA000005751413",
              "intOrdre": 300643,
              "etat": "VIGUEUR_ETEN",
              "title": "Panneaux d'affichage",
              "dateModif": null,
              "dateDebut": null,
              "dateFin": null,
              "sectionConsultee": false,
              "sections": [],
              "articles": [
                {
                  "executionTime": 0,
                  "dereferenced": false,
                  "id": "KALIARTI000005846019",
                  "cid": "KALIARTI000005846019",
                  "intOrdre": 42949,
                  "etat": "VIGUEUR_ETEN",
                  "num": "7",
                  "path": "/KALISCTA000005722130/KALISCTA000005751413/KALIARTI000005846019",
                  "pathTitle": [
                    "Clauses générales",
                    "Panneaux d'affichage"
                  ],
                  "content": "<p></p>   1. Des panneaux d'affichage grillagés ou vitrés de 0,50 sur 1 mètre, fermant à clef, seront réservés aux communications des syndicats et des délégués du personnel.<p></p><p></p><p></p>   2. Ces panneaux seront placés en des endroits accessibles au personnel, notamment aux portes d'entrée ou de sortie du personnel.<p></p><p></p>   Les règles suivantes seront appliquées pour l'utilisation de ces panneaux :<p></p><p></p>   a) Aucun document ne pourra être affiché en dehors des panneaux d'affichage ;<p></p><p></p>   b) Toutes les communications affichées devront être signées nominativement ;<p></p><p></p>   c) Les communications ne pourront se rapporter qu'à des informations d'ordre strictement professionnel ou syndical intéressant le personnel de l'établissement.<p></p><p></p>   Elles ne pourront en aucun cas prendre une forme ou un ton injurieux, avoir un caractère de polémique ou être de nature à apporter une perturbation dans la marche de l'entreprise.<p></p><p></p>   L'affichage sera effectué après communication à la direction qui ne pourra s'y opposer que si ces communications sortent manifestement du cadre défini ci-dessus.<p></p>",
                  "nota": null,
                  "comporteLiens": false,
                  "modificatorTitle": null,
                  "modificatorCid": null,
                  "modificatorDate": null,
                  "articleVersion": "1.0",
                  "type": null,