meta_name: "HelpRH"
meta_title: "HelpRH | Salariés, apprenez à faire respecter vos droits"
meta_description: "Qui n'a pas connu quelqu'un dans son entourage dont les droits se sont trouvés bafoués ? Help RH permet à chaque salarié de trouver facilement le texte de loi applicable à sa situation. Parce qu'un conseil juridique coûte cher, et n'est pas accessible à tous, cette App a pour objet de démocratiser l'accès au droit, et de vous permettre de mieux vous protéger."
meta_image: "HRHelp-logo.png" # should exist in `app/assets/images/`
